### ISSUE TITLE
Which kernel version & distribution do you use for development?

### ISSUE THREAD

**Issue by apatil** [bicomsystems/go-libzfs#1]
Hi @fkasumovic, I've had a little bit of trouble symlinking my kernel headers into the correct directory structure and was wondering which kernel & distro have been working for you.

Thanks!

**Comment by fkasumovic** [comment]
Hi,

It worked for me on ubuntu 12.04 and 14.04 64bit after installing
native ZFS for linux package

https://launchpad.net/~zfs-native/+archive/ubuntu/stable

I also use Gentoo, where its easier to compile different versions from source
including kernel. Currently I have gentoo with linux kernel 3.18 and ZFS v0.6.3-1.3.

I currently use go 1.4.2, didn’t test with 1.5 yet.

If you give me more details about your problem maybe I can help you.
