### ISSUE TITLE
zpool_find_import unavailable in ZoL 0.8.x

### ISSUE THREAD

**Issue by frebib** [bicomsystems/go-libzfs#12]
Upstream change: https://github.com/zfsonlinux/zfs/commit/e89f1295d#diff-bee8007a3f41acd4ba285b312ea24cc4L432

**Comment by frebib** [comment]
@lorenz, seeing as you don't have issues open on your fork

**Comment by lorenz** [comment]
@frebib I've enabled issues now, thanks!

**Comment by fkasumovic** [comment]
b1b9ae5
