### ISSUE TITLE
Fails to build on musl/alpine: unknown type name '__uint64_t'

### ISSUE THREAD

**Issue by frebib** [bicomsystems/go-libzfs#13]
Error:
```
# github.com/bicomsystems/go-libzfs
In file included from root/go/src/github.com/bicomsystems/go-libzfs/common.go:18:0:
./zpool.h:82:1: error: unknown type name '__uint64_t'
 __uint64_t set_zpool_vdev_online(zpool_list_t *pool, const char *path, int flags);
 ^~~~~~~~~~
```

Reproduce with:

```shell
docker run -ti --rm alpine sh
apk --no-cache add go git gcc musl-dev zfs-dev
go get -u github.com/bicomsystems/go-libzfs
```

**Comment by frebib** [comment]
Just as a test, I changed the type from `__uint64_t` to `uint64_t` and now I'm running into this problem. I'm apparently not very good at deciphering cgo errors because I can't tell what this is referring to: 

```
# github.com/bicomsystems/go-libzfs
cgo-gcc-prolog: In function '_cgo_74c0f6cd2834_Cmacro_stdout':
cgo-gcc-prolog:185:4: error: assignment of read-only variable 'r'
cgo-gcc-prolog:188:7: error: assignment of read-only member 'r'
```

**Comment by fkasumovic** [comment]
This is obvious due differences in clib you use, types that you have defined in headers like sys/types.h etc.. (muse). Second looks like issue related to C compiler checks, possible again  due clib used.

**Comment by frebib** [comment]
I should add that this didn't occur pre 0.7.x release and it doesn't occur either with the lorenz/go-libzfs that I tried either.
I'll have a go at bisecting

**Comment by frebib** [comment]
Bisecting revealed that 46ec88c0a85d09e2b290d5c78ae8c0fb3e2b7deb causes the issue. I can't work out why/seem to fix it.

Aside from that, the `__uint64_t` issue still persists and I can't quite fathom why it's not just `uint64_t`

**Comment by fkasumovic** [comment]
Yes,  uint64_t should be used. That's easy to fix, thanks.
In regards to compile issue, can you try what happens if you comment out SendSize function in sendrecv.go
I suspect there is source of issue. zfs_send function will print this out,  so I used little trick with pipe and redirection of stdout to get estimated send size. Because no other exported functions to get this estimation.

**Comment by frebib** [comment]
Commenting out `SendSize` makes it compile

**Comment by fkasumovic** [comment]
@frebib Thanks, this helps a lot to pin point problem. But since I have no same environment setup, I will have to ask you for one more favour. In this SendSize function/method, to replace C.fileno(C.stdout) with C.int(1) on lines 233, 234 & 239. I think this will resolve compile issue, and SendSize function should still work as expected.

**Comment by frebib** [comment]
As well as that change, I've had to remove the `C.fflush(C.stdout)` to make it compile, which is less than ideal

Whilst it is some work, may I suggest that it is worth writing what is effectively C code in a C function and calling that from Go instead?

Here is a full diff from my working tree (as well as a modification to the libzfs headers too :roll_eyes:)
```diff
diff --git a/sendrecv.go b/sendrecv.go
index 0bc5cf0..5e670ce 100644
--- a/sendrecv.go
+++ b/sendrecv.go
@@ -230,13 +230,13 @@ func (d *Dataset) SendSize(FromName string, flags SendFlags) (size int64, err er
        defer r.Close()
        go func() {
                var tmpe error
-               saveOut := C.dup(C.fileno(C.stdout))
-               if res := C.dup2(C.int(w.Fd()), C.fileno(C.stdout)); res < 0 {
+               saveOut := C.dup(C.STDOUT_FILENO)
+               if res := C.dup2(C.int(w.Fd()), C.STDOUT_FILENO); res < 0 {
                        tmpe = fmt.Errorf("Redirection of zfslib stdout failed %d", res)
                } else {
                        tmpe = d.send(FromName, w, &flags)
-                       C.fflush(C.stdout)
-                       C.dup2(saveOut, C.fileno(C.stdout))
+                       //C.fflush(C.stdout)
+                       C.dup2(saveOut, C.STDOUT_FILENO)
                }
                w.Close()
                errch <- tmpe
diff --git a/zpool.h b/zpool.h
index 33d416f..4b7808d 100644
--- a/zpool.h
+++ b/zpool.h
@@ -79,7 +79,7 @@ nvlist_ptr get_zpool_vdev_tree(nvlist_ptr nv);
 
 nvlist_ptr go_zpool_search_import(libzfs_handle_ptr zfsh, int paths, char **path, boolean_t do_scan);
 
-__uint64_t set_zpool_vdev_online(zpool_list_t *pool, const char *path, int flags);
+uint64_t set_zpool_vdev_online(zpool_list_t *pool, const char *path, int flags);
 int set_zpool_vdev_offline(zpool_list_t *pool, const char *path, boolean_t istmp, boolean_t force);
 int do_zpool_clear(zpool_list_t *pool, const char *device, u_int32_t rewind_policy);
 
diff --git a/zpool_vdev.c b/zpool_vdev.c
index 67bdbde..3d4427a 100644
--- a/zpool_vdev.c
+++ b/zpool_vdev.c
@@ -8,7 +8,7 @@
 #include "zpool.h"
 
 
-__uint64_t set_zpool_vdev_online(zpool_list_t *pool, const char *path, int flags) {
+uint64_t set_zpool_vdev_online(zpool_list_t *pool, const char *path, int flags) {
        vdev_state_t newstate = VDEV_STATE_UNKNOWN;
        zpool_vdev_online(pool->zph, path, flags, &newstate);
        return newstate;
```

**Comment by fkasumovic** [comment]
> As well as that change, I've had to remove the `C.fflush(C.stdout)` to make it compile, which is less than ideal

Yes, I wonder why would C.fflush(C.stdout) fail to compile? Do you have that error output?

> Whilst it is some work, may I suggest that it is worth writing what is effectively C code in a C function and calling that from Go instead?

Yes, I think this could be wrapped like "int redirect_stdout(int, int), restore_stdout(int, int)" functions.
Or otherwise whole SendSize should be implemented in C

**Comment by frebib** [comment]
> Do you have that error output?

It was the same output as before:
```
cgo-gcc-prolog: In function '_cgo_74c0f6cd2834_Cmacro_stdout':
cgo-gcc-prolog:185:4: error: assignment of read-only variable 'r'
cgo-gcc-prolog:188:7: error: assignment of read-only member 'r'
```

Perhaps I should report this upstream to Alpine/musl and see if they can reproduce/fix it?

**Comment by fkasumovic** [comment]
> Perhaps I should report this upstream to Alpine/musl and see if they can reproduce/fix it?

I don't think this is Alpine/musl issue, but more cgo in combination with musl. I will investigate more, maybe suggested wrapper is fix.

Also what version of go did you use ?

**Comment by frebib** [comment]
`go version go1.10.5 linux/amd64`, the latest from `alpine:3.8`

**Comment by fkasumovic** [comment]
Ok, check and try 7482756 for changes needed to build on musl/alpine.
If it will work and in combination with docker is different issue :-).
But will be interesting to find out. Otherwise, I would recommend trying with glibc.

**Comment by frebib** [comment]
Yeah that builds just fine. Thanks for putting up with my/Alpine's shit.
Sorry that you had to mutilate your code to make it work.

**Comment by fkasumovic** [comment]
Np. I’m glad I could help. Except, its better if it works  on more linux distributions. 😊 I’ll come up with something prettier (I hope), just wanted to make clear whats needed for this to work or build at least. 

Thank you for helping and debugging.
