### ISSUE TITLE
Help understanding zpool state

### ISSUE THREAD

**Issue by jsirianni** [bicomsystems/go-libzfs#14]
Hello, when I run `zpool status` I see
```
root@pve-1:~# zpool status -v
  pool: data
 state: ONLINE
  scan: none requested
config:

	NAME                      STATE     READ WRITE CKSUM
	data                      ONLINE       0     0     0
	  scsi-35002538e402d9b06  ONLINE       0     0     0
	  scsi-350025388a05aeb61  ONLINE       0     0     0

```

When I call call `pool.Status()` I see "state: ACTIVE". 
```
func check() error {
    globalPools, err := zfs.PoolOpenAll()
    defer zfs.PoolCloseAll(globalPools)
    if err != nil {
        return err
    }

    for _, pool := range globalPools {
        state, err := pool.State()
        if err != nil {
            return err
        }
        fmt.Println("pool state:", state)
    }

    return nil
}
```
```
pool state: ACTIVE
```

I would expect to see pool state "ONLINE", not "ACTIVE". Am I doing this incorrectly?

**Comment by fkasumovic** [comment]
Output of zpool command maps root vdev state to string and shows that as status

Equivalent in go is:

First you need to obtain vdevs stat from pool

// Assuming pool is opened
vdevs, err := pool.VDevTree()
if err != nil {
     panic(err.Error())
}
println(PoolStateToName(vdevs.Stat))

// PoolStateToName map vdev state to string state of pool
func PoolStateToName(stat zfs.VDevStat) string {
	switch stat.State {
	case zfs.VDevStateClosed:
		fallthrough
	case zfs.VDevStateOffline:
		return "OFFLINE"
	case zfs.VDevStateRemoved:
		return "REMOVED"
	case zfs.VDevStateCantOpen:
		if stat.Aux == zfs.VDevAuxCorruptData || stat.Aux == zfs.VDevAuxBadLog {
			return "FAULTED"
		} else if stat.Aux == zfs.VDevAuxSplitPool {
			return "SPLIT"
		} else {
			return "UNAVAIL"
		}
	case zfs.VDevStateFaulted:
		return "FAULTED"
	case zfs.VDevStateDegraded:
		return "DEGRADED"
	case zfs.VDevStateHealthy:
		return "ONLINE"
	}
	return "UNKNOWN"
}
