### ISSUE TITLE
libzfs is not a stable interface

### ISSUE THREAD

**Issue by trisk** [bicomsystems/go-libzfs#2]
libzfs is explicitly _not_ a stable interface; libzfs_core (formerly libzfs2) is intended to provide one when it is complete. The `zfs(1M)` and `zpool(1M)` userspace tools actually have a stability commitment.

**Comment by fkasumovic** [comment]
Thank you for your feedback. Still its user interface not API. Single character may mean nothing to user in output, but then it depends lot on how well you implemented parsing when using from library or applications. I don't plan to strong defend my choice as only right thing to do or that I am not wrong. Just, it feals wrong to build library relaying on user cli output. Thats how I see it. This is to be go wraper for libzfs. Hope i will be able to do same once libzfs2 is there. Till then I simple don't see better way to do this.
