### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by mikroskeem** [bicomsystems/go-libzfs#22]
https://gist.github.com/mikroskeem/ffbb3b15fb074f5c71bec33e24f35857

Using Arch Linux, ZFS 0.8.2, Go 1.13.4 and Linux 5.3.10

**Comment by fkasumovic** [comment]
Check your go mod file in the project, it seems like go mod is trying to build from dev-zfs-0.7.x branch from where this v0.2.3 tag comes from. I just pushed tag v0.2.4  to the master branch, try changing the tag to v0.2.4 in go mod file.

**Comment by mikroskeem** [comment]
Yep, go attempted to build v0.2.3. While trying to `go get` again didn't have any effect (probably because of caching?), then adding `replace github.com/bicomsystems/go-libzfs => github.com/bicomsystems/go-libzfs v0.2.4` to go.mod did the trick.
