### ISSUE TITLE
ZPool properties are not parsable

### ISSUE THREAD

**Issue by prometherion** [bicomsystems/go-libzfs#25]
I noticed a difference between values provided by `zfs.Dataset` properties and `zfs.Pool` ones: basically, on ZPool instances, quantity resources like space allocated or space size are expressed as human-readable value, as opposed to what's happening with Dataset where I can get bytes values with ease.

I tried to dig deeper on the C implementation but hadn't luck: do you plan to fill this gap of properties presentation?

JFI ZPool allows to retrieve parsable values:
```
# zpool list -p
NAME     SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
mypool  1006632960  419840  1006213120        -         -      0      0   1.00    ONLINE  -
```

**Comment by fkasumovic** [comment]
It's a mistake in the call to libzfs C function C.zpool_get_prop , last argument 'boolean_t literal' should be B_TRUE.
Will be fixed, thank you for reporting this.

**Comment by prometherion** [comment]
thanks @fkasumovic, just opened PR #26

**Comment by prometherion** [comment]
@fkasumovic is this hotfix going to be released for a new version?
Can you give an ETA?

**Comment by fkasumovic** [comment]
> @fkasumovic is this hotfix going to be released for a new version?
> Can you give an ETA?

https://github.com/bicomsystems/go-libzfs/releases/tag/v0.3.0
