### ISSUE TITLE
Wrong pool status reported?

### ISSUE THREAD

**Issue by sandstreamer** [bicomsystems/go-libzfs#28]
When running `pool.Status()`: 
```
allPools, err := zfs.PoolOpenAll()
if err != nil {
	println(err)
}

for _, pool := range allPools {
	status, err := pool.Status()
	if err != nil {
		println(err)
	}
	state, err := pool.State()
	if err != nil {
		println(err)
	}
	name, err := pool.Name()
	if err != nil {
		println(err)
	}
	fmt.Printf("Pool name: %s\n", name)
	fmt.Printf("Status: %s, State: %s\n", status, state)

}
zfs.PoolCloseAll(allPools)
```
I get this output:
```
ps@ubuntu-srv-zfs:~/go/src/testzfs$ ./testzfs
Pool name: tank2
Status: REMOVED_DEV, State: ACTIVE
```

**REMOVED_DEV** status seems wrong given that I have no issues with my pool:
```
ps@ubuntu-srv-zfs:~$ sudo zpool status -v
  pool: tank2
 state: ONLINE
  scan: scrub repaired 0B in 9h19m with 0 errors on Sun Dec 15 09:19:05 2019
config:

	NAME                        STATE     READ WRITE CKSUM
	tank2                       ONLINE       0     0     0
	  mirror-0                  ONLINE       0     0     0
	    wwn-0x5000c500a42a268c  ONLINE       0     0     0
	    wwn-0x5000c500afedf367  ONLINE       0     0     0
	  mirror-1                  ONLINE       0     0     0
	    wwn-0x50014ee25e4b10c8  ONLINE       0     0     0
	    wwn-0x50014ee2b76f2200  ONLINE       0     0     0

errors: No known data errors
```
Am I doing something wrong here? I'm expecting to get Status: OK, given my understanding of the source code in zpool.go.

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu Server
Distribution Version	| 18.04.3 LTS
Linux Kernel	| GNU/Linux 4.15.0-72-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.6
SPL Version	| 0.7.5-1ubuntu2
go-libzfs tag	| v0.2.3

**Comment by fkasumovic** [comment]
Hm, interesting. Well as you can see if you follow implementation it simple returns value from libzfs C.zpool_get_status(). And this function finds this problem, not necessary displayed by user space tools maybe. Did you previously reconfigured pool in some way?

I tried to replicate with code above on zfs 0.7.13 and everything worked as expected
this is output:

CaveNebula ~/tesst2 # go run main.go
Pool name: SYSTEM-5ccc
Status: OK, State: ACTIVE
Pool name: NETSTOR
Status: OK, State: ACTIVE
CaveNebula ~/tesst2 # zpool status
  pool: NETSTOR
 state: ONLINE
  scan: none requested
config:

	NAME          STATE     READ WRITE CKSUM
	NETSTOR       ONLINE       0     0     0
	  mirror-0    ONLINE       0     0     0
	    NETSTOR1  ONLINE       0     0     0
	    NETSTOR2  ONLINE       0     0     0

errors: No known data errors

  pool: SYSTEM-5ccc
 state: ONLINE
  scan: none requested
config:

	NAME                                      STATE     READ WRITE CKSUM
	SYSTEM-5ccc                               ONLINE       0     0     0
	  scsi-36000c297308717a408787ca87d98cef4  ONLINE       0     0     0

errors: No known data errors

**Comment by sandstreamer** [comment]
Thanks for investigating!
The only change in the pool I have done is to add a second mirror vdev and then a couple of weeks later replaced one faulty device using command:
`replace tank2 /dev/disk/by-id/wwn-0x50014ee2b76f21bc /dev/disk/by-id/wwn-0x50014ee25e4b10c8`

To test with a different pool I created a new pool with sparse files:
```
ps@ubuntu-srv-zfs:~$ truncate --size 10G disk1.img disk2.img

ps@ubuntu-srv-zfs:~$ sudo zpool create testpool mirror \
  `pwd`/disk1.img \
  `pwd`/disk2.img

```
Status:
```
ps@ubuntu-srv-zfs:~/go/src/testzfs$ sudo zpool status -v
  pool: tank2
 state: ONLINE
  scan: scrub repaired 0B in 12h33m with 0 errors on Wed Jan 15 12:33:16 2020
config:

	NAME                        STATE     READ WRITE CKSUM
	tank2                       ONLINE       0     0     0
	  mirror-0                  ONLINE       0     0     0
	    wwn-0x5000c500a42a268c  ONLINE       0     0     0
	    wwn-0x5000c500afedf367  ONLINE       0     0     0
	  mirror-1                  ONLINE       0     0     0
	    wwn-0x50014ee25e4b10c8  ONLINE       0     0     0
	    wwn-0x50014ee2b76f2200  ONLINE       0     0     0

errors: No known data errors

  pool: testpool
 state: ONLINE
  scan: none requested
config:

	NAME                        STATE     READ WRITE CKSUM
	testpool                    ONLINE       0     0     0
	  mirror-0                  ONLINE       0     0     0
	    /home/petter/disk1.img  ONLINE       0     0     0
	    /home/petter/disk2.img  ONLINE       0     0     0

errors: No known data errors
```
Output:
```
ps@ubuntu-srv-zfs:~/go/src/testzfs$ go run testzfs.go 
Pool name: testpool
Status: REMOVED_DEV, State: ACTIVE
Pool name: tank2
Status: REMOVED_DEV, State: ACTIVE
```

I get status REMOVED_DEV for both pools..

**Comment by fkasumovic** [comment]
Ok I found the reason, there is a change between 0.7.5 and latest 0.7.13 release on zfs project
https://github.com/zfsonlinux/zfs/commit/3eb3a13628d3d58b0294e4e0c0e3b47483a4053e

So you either have to update zfs to latest 0.7.13 release, or fork go-libzfs and remove line 97 in common.go
	PoolStatusIOFailureMap                        /* ailed MMP, failmode not 'panic' */

This status did not exist in 0.7.5 and is reason for wrong status you get.

**Comment by sandstreamer** [comment]
Commented out line 97 in common.go + lines 1136-1137 in zpool.go, then it works as expected:
```
ps@ubuntu-srv-zfs:~/go/src/testzfs$ go run testzfs.go
Pool name: tank2
Status: OK, State: ACTIVE
```
Thanks again!
