### ISSUE TITLE
go get error with go 1.6

### ISSUE THREAD

**Issue by cmosetick** [bicomsystems/go-libzfs#3]
Just tried `go get` with this on go 1.6:

```
go get github.com/bicomsystems/go-libzfs
# github.com/bicomsystems/go-libzfs
src/gocode/src/github.com/bicomsystems/go-libzfs/common.go:16:10: fatal error: 'libzfs.h' file not found
#include <libzfs.h>
         ^
1 error generated.
```

Platform
OS X 10.11.3
`go version go1.6 darwin/amd64`
Open ZFS version:
`brew cask info openzfs`
$ openzfs: 1.4.5

**Comment by fkasumovic** [comment]
Looks like you will have to install Open ZFS from source, to get all development files on OSX. :-(

https://openzfsonosx.org/wiki/Install#Installing_from_Source
