### ISSUE TITLE
ZFS 2.0 support

### ISSUE THREAD

**Issue by jsirianni** [bicomsystems/go-libzfs#35]
I have a project that depends on go-libzfs. I am currently refreshing it, and was hoping to build against the latest openzfs but I seem to get some errors:
```
Step 10/14 : RUN GOOS=linux GOARCH=amd64 go test ./...
 ---> Running in d1570b2a8acc
...
/root/go/pkg/mod/github.com/bicomsystems/go-libzfs@v0.3.5/zpool.go:1108:39: could not determine kind of name for C.pool_initialize_func_t
/root/go/pkg/mod/github.com/bicomsystems/go-libzfs@v0.3.5/zpool.go:1108:5: could not determine kind of name for C.zpool_initialize
```

I can build against an older version, but am wondering if 2.0 is on the roadmap? If contributors are needed, please let me know. I am not at all experienced with C but I do have plenty of Go experience and access to systems running OpenZFS on Linux and FreeBSD. I am happy to deploy test systems.

**Comment by fkasumovic** [comment]
Hi @jsirianni,

Please try with dev-zfs-2.0.x branch.

**Comment by grimmy** [comment]
So I built and tested the `DatasetOpenAll` example and the library is only seeing my root dataset.

```
$ sudo ./zfstest 
                       spectre | filesystem
$ sudo zfs list
NAME           USED  AVAIL     REFER  MOUNTPOINT
spectre        202G   248G       96K  /spectre
spectre/home   202G   248G      182G  /home
```

I ran it with sudo to verify it wasn't a permission issue. `spectre/home` is encrypted, but I can still see it via `/sbin/zfs list` as a normal user so it's just missing here.

**Comment by fkasumovic** [comment]
Hi @grimmy ,

I can probably help, or figure out what the bug is, but just to avoid guesswork by me can you post your zfstest code here?

**Comment by grimmy** [comment]
It's literally the example from the godoc.

```go
package main

import (
	"fmt"

	zfs "github.com/bicomsystems/go-libzfs"
)

func main() {
	datasets, err := zfs.DatasetOpenAll()
	if err != nil {
		panic(err.Error())
	}
	defer zfs.DatasetCloseAll(datasets)

	// Print out path and type of root datasets
	for _, d := range datasets {
		path, err := d.Path()
		if err != nil {
			panic(err.Error())
		}
		p, err := d.GetProperty(zfs.DatasetPropType)
		if err != nil {
			panic(err.Error())
		}
		fmt.Printf("%30s | %10s\n", path, p.Value)
	}

}
```

go-libzfs was installed via `go get github.com/bicomsystems/go-libzfs@dev-zfs-2.0.x`

But here's my `go.mod` for completeness
```
module zfstest

go 1.15

require github.com/bicomsystems/go-libzfs v0.3.4-0.20210120103208-f957d22f5c47
```

**Comment by fkasumovic** [comment]
@grimmy Yes, that will print the only dataset on the root level, an example does not demonstrate listing all recursive datasets, thanks for pointing it out.
But if you want a recursive print of all datasets, check this function as an example:

https://github.com/bicomsystems/go-libzfs/blob/271cb4eeeb7f6738b9303c67ebb76cf47f46c922/zfs_test.go#L16

**Comment by grimmy** [comment]
Ah okay, I was missing that `Dataset` has a child parameter. It might be nice if the godoc for `DatasetOpenAll()` would mention that it just returns top level datasets, but that the children are available as the `Children` property.

**Comment by fkasumovic** [comment]
@grimmy Pull request? 🙂

**Comment by grimmy** [comment]
I'm already shaving a yak which led me to this library... so no promises ;)
