### ISSUE TITLE
zfs-2.1.x compatibility

### ISSUE THREAD

**Issue by Tualua** [bicomsystems/go-libzfs#36]
Hello! Is it possible to update for zfs-2.1.x?

    # go get github.com/bicomsystems/go-libzfs
    go: downloading github.com/bicomsystems/go-libzfs v0.3.5
    # github.com/bicomsystems/go-libzfs
    zfs.c: In function ‘dataset_rename’:
    zfs.c:136:43: error: incompatible type for argument 3 of ‘zfs_rename’
      return zfs_rename(dataset->zh, new_name, recur, force_unm);
                                               ^~~~~
    In file included from zfs.c:5:
    /usr/include/libzfs/libzfs.h:661:53: note: expected ‘renameflags_t’ {aka ‘struct renameflags’} but argument is of type ‘boolean_t’ {aka         ‘enum <anonymous>’}
     extern int zfs_rename(zfs_handle_t *, const char *, renameflags_t);
                                                         ^~~~~~~~~~~~~
    zfs.c:136:9: error: too many arguments to function ‘zfs_rename’
      return zfs_rename(dataset->zh, new_name, recur, force_unm);
             ^~~~~~~~~~
    In file included from zfs.c:5:
    /usr/include/libzfs/libzfs.h:661:12: note: declared here
     extern int zfs_rename(zfs_handle_t *, const char *, renameflags_t);

ZFS:

    # modinfo zfs
    filename:       /lib/modules/5.4.17-2136.302.7.2.el8uek.x86_64/extra/zfs.ko.xz
    version:        2.1.2-1

Go:

    # go version
    go version go1.17.6 linux/amd64

**Comment by fkasumovic** [comment]
Not yet, but soon, you can try with 
go get github.com/bicomsystems/go-libzfs@dev-zfs-2.0.x

If there are not too many breaking changes in libzfs it might work for what you need.

Anyway, I was about to check on this during the weekend, since these changes are usually not so big and require small corrections in go-libzfs @dev-zfs-2.1.x branch should be available by Monday.

**Comment by scottlaird** [comment]
I'm seeing a persistent failure with `PoolOpen` and `PoolOpenAll` with 2.1:

```
panic: runtime error: index out of range [33] with length 33

goroutine 1 [running]:
github.com/bicomsystems/go-libzfs.(*Pool).ReloadProperties(0xc0000dde78)
        /home/scott/go/pkg/mod/github.com/bicomsystems/go-libzfs@v0.3.4-0.20210120103208-f957d22f5c47/zpool.go:531 +0x56e
github.com/bicomsystems/go-libzfs.PoolOpen({0x4cce4d, 0xc0001a4008})
        /home/scott/go/pkg/mod/github.com/bicomsystems/go-libzfs@v0.3.4-0.20210120103208-f957d22f5c47/zpool.go:160 +0x9f
```

Changing the `+1` to `+2` a [few lines above](https://github.com/bicomsystems/go-libzfs/blob/f957d22f5c4715ac0e94a6ee63cc83e3c3bfa30d/zpool.go#L528) seems to fix that, but it doesn't feel like a great fix.

**Comment by fkasumovic** [comment]
@Tualua @scottlaird  
**[_dev-zfs-2.1.x_](https://github.com/bicomsystems/go-libzfs/tree/dev-zfs-2.1.x)** is now ready, try updating your projects

```sh
go get -u github.com/bicomsystems/go-libzfs@dev-zfs-2.1.x
```

Let me know if you find more issues, and thank you for reporting this.

**Comment by Tualua** [comment]
> Let me know if you find more issues, and thank you for reporting this.

Looks like it is working fine.

I tested open/close dataset, clone, destroy, snapshot and getting dataset properties.

The only minor issue I got is errors in debug console when I restart debugger in vscode

    2022-02-06T14:50:13+08:00 error layer=debugger error loading binary "/lib64/libzfs.so.4": could not parse .eh_frame section: unknown CIE_id 0xfffffff4 at 0x0
    2022-02-06T14:50:13+08:00 error layer=debugger error loading binary "/lib64/libzpool.so.5": could not parse .eh_frame section: unknown CIE_id 0xb1b8d7e4 at 0x0
    2022-02-06T14:50:13+08:00 error layer=debugger error loading binary "/lib64/libnvpair.so.3": could not parse .eh_frame section: unknown CIE_id 0xfffffff4 at 0x0
    2022-02-06T14:50:13+08:00 error layer=debugger error loading binary "/lib64/libzfs_core.so.3": could not parse .eh_frame section: unknown CIE_id 0xfffffff4 at 0x0
    2022-02-06T14:50:13+08:00 error layer=debugger error loading binary "/lib64/libuutil.so.3": could not parse .eh_frame section: unknown CIE_id 0xfffffff4 at 0x0

I'm not sure if this is related to your library

**Comment by fkasumovic** [comment]
@Tualua Yeah, I think this is related to the binaries debug information on your system. 
If you find out this is go-libzfs related please open a new issue. 
Thank you for reporting back. I will close this issue now.
