### ISSUE TITLE
Status strings?

### ISSUE THREAD

**Issue by deitch** [bicomsystems/go-libzfs#41]
The `zpool status` command returns not only the status code, but also some fairly standard text describing the issue and recovery options.

Would you consider including those texts as `const string` in the library, so that a consumer of the library using `pool.Status()` can have those strings? I would be happy to open a PR for it.

The strings are all [here](https://github.com/openzfs/zfs/blob/35d81a75a8c13e011e19fd12cf553d9c5849386e/cmd/zpool/zpool_main.c#L8192-L8522).

Granted, this is a library and _not_ a CLI, which would need to report those, but the strings are useful for anyone building on this.

**Comment by fkasumovic** [comment]
@deitch Good idea, PR is welcome

Thank you.

**Comment by fkasumovic** [comment]
#42
