### ISSUE TITLE
User Dataset Properties

### ISSUE THREAD

**Issue by danielkucera** [bicomsystems/go-libzfs#6]
Hi,

I am thinking about a solution how to set User Dataset Properties through this api (https://pthree.org/2013/01/02/zfs-administration-part-xvi-getting-and-setting-properties/).

Do you have any idea?

**Comment by danielkucera** [comment]
It would be nice if I could set property by name and not only by type defined in library

**Comment by fkasumovic** [comment]
https://godoc.org/github.com/bicomsystems/go-libzfs#Dataset.SetUserProperty
